services:

  db-terceros:
    image: postgres:15-alpine
    container_name: db_terceros
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_terceros_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    networks:
      - ivent-network

  ms-terceros:
    container_name: ms-terceros
    build:
      context: ../../../
      dockerfile: ./apps/ms-terceros/deploy/Dockerfile
      args:
        - MICROSERVICIO=ms-terceros
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db-terceros:5432/${DB_NAME}?schema=public
      DB_HOST: db-terceros
    expose:     
      - "3000"
    depends_on:
      - db-terceros
    networks:
      - ivent-network

volumes:
  postgres_terceros_data:

networks:
  ivent-network:
    driver: bridge
    external: true