services:

  db-logistica:
    image: postgres:15-alpine
    container_name: db_logistica
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_logistica_data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      - ivent-network

  ms-logistica:
    container_name: ms-logistica
    build:
      context: ../../../
      dockerfile: ./apps/ms-logistica/deploy/Dockerfile
      args:
        - MICROSERVICIO=ms-logistica
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db-logistica:5432/${DB_NAME}?schema=public
      DB_HOST: db-logistica
    expose:     
      - "3000"
    depends_on:
      - db-logistica
    networks:
      - ivent-network

volumes:
  postgres_logistica_data:

networks:
  ivent-network:
    driver: bridge
    external: true