controller:
  installPlugins: false

  admin:
    password: "admin"
  
  serviceType: NodePort
  nodePort: 32000

  # 1. Forzamos a ejecutar como root para tener permisos sobre el socket de Docker
  runAsUser: 0
  fsGroup: 0

  # 2. Instalamos el cliente de Docker antes de arrancar y ajustamos permisos
  initializeCommand: |
    apt-get update && apt-get install -y docker.io
    chown -R 0:0 /var/jenkins_home

  sidecars:
    configAutoReload:
      enabled: false

  # 3. Conectamos el motor de Docker del VPS directamente al Pod de Jenkins
  extraVolumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
  extraVolumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

persistence:
  enabled: true
  size: 8Gi  
  storageClass: "microk8s-hostpath"