controller:
  admin:
    password: "admin"
  
  serviceType: NodePort
  nodePort: 32000

  runAsUser: 0
  fsGroup: 0

  # Desactivamos los sidecars que fallan por certificados SSL
  sidecars:
    configAutoReload:
      enabled: false

  # Solo montamos el socket de Docker
  extraVolumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
  extraVolumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

persistence:
  enabled: true
  size: 8Gi  
  storageClass: "microk8s-hostpath"