services:
  db-analytics:
    image: postgres:15-alpine
    container_name: db_analytics
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - ivent-network

  ms-analytics:
    container_name: ms-analytics
    build:
      context: ../../../
      dockerfile: ./apps/ms-analytics/deploy/Dockerfile
      args:
        - MICROSERVICIO=ms-analytics
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db-analytics:5432/${DB_NAME}?schema=public
      DB_HOST: db-analytics
      NATS_SERVERS: ${NATS_SERVERS}
    expose:     
      - "3000"
    depends_on:
      - db-analytics
    networks:
      - ivent-network

volumes:
  postgres_analytics_data:

networks:
  ivent-network:
    external: true